#map layouts are [Left, Right, Top, Bottom, Have Spawned]
map_1 = ["room_1", False, True, False, True, False]
map_2 = ["room_2", True, True, False, False, False]
map_3 = ["room_3", False, True, True, False, False]
map_4 = ["room_4", True, True, True, True, False]
map_5 = ["room_5", True, False, False, True, False]
map_6 = ["room_6", False, True, False, False, False]
map_7 = ["room_7", True, False, True, False, False]
map_8 = ["room_8", True, True, True, False, False]
map_9 = ["room_9", True, True, False, True, False]
map_10 = ["room_10", True, False, True, True, False]
map_11= ["room_11", False, True, True, True, False]
map_12 = ["room_12", False, False, True, False, True]
map_13 = ["room_13", True, False, False, False, False]
map_14 = ["room_14", False, False, False, True, False]
list_of_all_rooms = [map_1, map_2, map_3, map_4, map_5, map_6, map_7, map_8, map_9, map_10, map_11, map_12, map_13, map_14]

